# syntax=docker/dockerfile:1

# this can be changed for what server you want to use (i.e. NodeJS)
FROM httpd

# copy files in src to the Apache server's document folder
COPY ./src/ /usr/local/apache2/htdocs/