version: '3.1'

services:
  backend:
    build: backend
    restart: always
    ports:
      - "9000:8000"
    depends_on:
      - postgres
    networks:
      - main

  postgres:
    build: sql
    restart: always
    environment:
      POSTGRES_PASSWORD: 'fluffyunicorn'
    ports:
      - "5432:5432"
    networks:
      - main

networks:
  main:
    driver: bridge