version: '3.1'

services:
  frontend:
    build: frontend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - backend

  backend:
    build: backend
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - postgres

  postgres:
    build: sql
    restart: always
    environment:
      POSTGRES_PASSWORD: 'Z!XQ$S#69o#x*r'
    ports:
      - "5432:5432"