# Test your FastAPI endpoints

GET http://127.0.0.1:9000/
Accept: application/json

###

GET http://127.0.0.1:9000/depots/
Accept: application/json
###

POST http://127.0.0.1:9000/sql/write
Accept: application/json

INSERT INTO depots (id, city, capacity, truck_spaces, plane_spaces, train_spaces) VALUES (0, 'Chicago, IL', 2200, 20, 2, 8)
###